### ISSUE TITLE
AWS task queuer container error

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/etl2#15]
Timing issue?

```
Running queue: []
2016-12-09 08:45:47 - aws_task_queuer.py:103 (dispatch) - Running jobs deficit (need 2), launching
2 more
Traceback (most recent call last):
  File "python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bin/aws_task_queuer.py", line 248, in <module>
    task_queue = dispatch(sorted(task_queue, key=lambda x: x['event_date']))
  File "bin/aws_task_queuer.py", line 142, in dispatch
    'value': "json-file,awslogs"
  File "site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterException) when calling the RunTask operation: No Container Instances were found in your cluster.
```

**Comment by kxyne** [comment]
We're not using this functionality anymore.
